obj-$(CONFIG_CPU_FREQ_GOV_COMMON)				:= cpufreq_governor.o

obj-$(CONFIG_CPU_FREQ_GOV_PERFORMANCE)			+= cpufreq_performance.o
obj-$(CONFIG_CPU_FREQ_GOV_POWERSAVE)			+= cpufreq_powersave.o
obj-$(CONFIG_CPU_FREQ_GOV_USERSPACE)			+= cpufreq_userspace.o
obj-$(CONFIG_CPU_FREQ_GOV_ONDEMAND)				+= cpufreq_ondemand.o
obj-$(CONFIG_CPU_FREQ_GOV_CONSERVATIVE)			+= cpufreq_conservative.o
obj-$(CONFIG_CPU_FREQ_GOV_INTERACTIVE)			+= cpufreq_interactive.o
obj-$(CONFIG_CPU_FREQ_GOV_BLUACTIVE)			+= cpufreq_bluactive.o
obj-$(CONFIG_CPU_FREQ_GOV_CONSERVATIVE)			+= cpufreq_conservative.o
obj-$(CONFIG_CPU_FREQ_GOV_DARKNESS)				+= cpufreq_darkness.o
obj-$(CONFIG_CPU_FREQ_GOV_ELEMENTALX)			+= cpufreq_elementalx.o
obj-$(CONFIG_CPU_FREQ_GOV_IMPULSE)				+= cpufreq_impulse.o
obj-$(CONFIG_CPU_FREQ_GOV_INTELLIACTIVE)		+= cpufreq_intelliactive.o
obj-$(CONFIG_CPU_FREQ_GOV_LIONFISH)				+= cpufreq_lionfish.o 
obj-$(CONFIG_CPU_FREQ_GOV_NIGHTMARE)			+= cpufreq_nightmare.o
obj-$(CONFIG_CPU_FREQ_GOV_YANKACTIVE)			+= cpufreq_yankactive.o
obj-$(CONFIG_CPU_FREQ_GOV_ZZMOOVE)				+= cpufreq_zzmoove.o